# Generated by Django 5.0.3 on 2024-03-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_string', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'policy_string',
            },
        ),
    ]
