# Generated by Django 5.0.3 on 2024-03-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vom_receiver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='react',
            table='VOM_POLICIES',
        ),
    ]
